🚀 feat: added base document model and module tests
powerhouse-inc/codegen pull request #9
Opened 2023-10-11 20:03 UTC by gpuente

## Description:

- Added auto generated tests for base document model
- Added auto generated tests for modules
- Added auto generated mock input data

<img width="267" alt="Screenshot 2023-10-11 at 17 02 31" src="https://github.com/powerhouse-inc/powerhouse/assets/20387722/924e5f6c-e88b-4fd1-8dc4-649b6b4010b1">

<img width="573" alt="Screenshot 2023-10-11 at 17 01 26" src="https://github.com/powerhouse-inc/powerhouse/assets/20387722/0b77b7f2-f8c5-4ecf-82f3-492c4adb27b4">

2023-10-12 08:52 UTC, acaldas requested changes

2023-10-12 08:52 UTC, acaldas commented on package.json
> +        "@anatine/zod-mock": "^3.13.2",
Let's create our own generateMock utility so that these dependencies don't have to be explicitly installed on the libs using the powerhouse package.

2023-10-12 08:52 UTC, acaldas commented on src/codegen/.hygen/templates/powerhouse/generate-document-model-module/customTest.esm.t
> +import { generateMock } from '@anatine/zod-mock';
So this would become import { generateMock } from '@powerhousedao/powerhouse';

2023-10-13 18:50 UTC, gpuente commented on package.json
> +        "@anatine/zod-mock": "^3.13.2",
added `generateMock` utility in this commit: [b06814b](https://github.com/powerhouse-inc/powerhouse/pull/9/commits/b06814bb213e9b815e6b80c68572d8143db2e77a)

2023-10-13 18:50 UTC, gpuente commented on src/codegen/.hygen/templates/powerhouse/generate-document-model-module/customTest.esm.t
> +import { generateMock } from '@anatine/zod-mock';
added `generateMock` utility in this commit: [b06814b](https://github.com/powerhouse-inc/powerhouse/pull/9/commits/b06814bb213e9b815e6b80c68572d8143db2e77a)

2023-10-16 09:06 UTC, acaldas approved these changes

2023-10-16 09:06 UTC, merged